const OWNERS = ["Rosa","Wedja","Aianny","Ju/Wellington","Joao Lucas","Kauany","Evane"];
const COLORS = {"Rosa":"#e91e63","Wedja":"#c28b00","Aianny":"#2476c5","Ju/Wellington":"#238b45","Joao Lucas":"#e56b18","Kauany":"#7a3db8","Evane":"#008c88","Sem dono":"#6c7280"};
const INITIAL_INVOICES = [
  {id:"abril-2026",month:"Abril",year:2026,total:8269.36,file:"SuaFaturaCartaoBV_abril_26_unlocked_260426_143109.pdf",detail:"Fatura e anotações disponíveis",hasBlob:false,status:"Histórico"},
  {id:"maio-2026",month:"Maio",year:2026,total:7658.61,file:"SuaFaturaCartaoBV_maio_26_unlocked.pdf",detail:"Fatura e anotações disponíveis",hasBlob:false,status:"Histórico"},
  {id:"agosto-2026",month:"Agosto",year:2026,total:6104.29,file:"DOC-20260727-WA0093_260729_111147.pdf",detail:"Fatura anotada disponível",hasBlob:false,status:"Histórico"},
  {id:"setembro-2026",month:"Setembro",year:2026,total:7289.55,file:"SuaFaturaCartaoBV_setembro_26_unlocked.pdf",detail:"Fatura atual classificada",hasBlob:false,status:"Classificada"}
];
const t=(id,date,merchant,installment,location,amount,owner="",note="",extra={})=>({id,date,merchant,installment,location,amount,owner,note,dueNow:amount,...extra});
const INITIAL = [
 t(1,"29/07","SEGURO CARTÃO PROTEGIDO","","-",15.90,"Rosa","seguro do cartão"),
 t(2,"06/08","A BONNER CONCEPT","01/03","Frei Paulo",144.52,"Wedja"),
 t(3,"06/08","ENCONTRO DO SOL HOME","01/10","Maceió",203.39,"Wedja","construção"),
 t(4,"06/08","MP*33908954EWERT","01/06","Maceió",102.45,"Wedja","construção"),
 t(5,"07/08","MP *MEGABALCOESEEXPOSI","01/03","São Paulo",88.95,"Wedja","Mercado Livre"),
 t(6,"07/08","MP *MERCADOLIVRE","01/10","São Paulo",119.99,"Wedja","Mercado Livre"),
 t(7,"08/08","FU JIAN PRESENTES","","Maceió",78,"Rosa","carteiras compradas para Duda"),
 t(8,"08/08","LauraBeatriz","01/02","Maceió",60,"Rosa","vitamina comprada na JR Suplementos"),
 t(9,"10/08","MP*TECHMUNDO","01/05","Maceió",168.21,"Wedja","Techmundo"),
 t(10,"12/08","CARDOSO ELETRÔNICA","01/04","Maceió",95,"Ju/Wellington","som comprado por Wellington"),
 t(11,"12/08","DANIEL ARCANJO DOS SA","","Maceió",72),
 t(12,"12/08","SUPERMERCADO SÃO DOMIN","01/02","Maceió",124.08,"Ju/Wellington","supermercado"),
 t(13,"16/08","PEIXARIA RJ","","Maceió",86.50,"Ju/Wellington","peixaria"),
 t(14,"16/08","POSTO CARANGO","01/02","Maceió",50,"Ju/Wellington","combustível"),
 t(15,"17/08","Cartão de TODOS","","Ipatinga",33.40,"Rosa","Cartão de Todos"),
 t(16,"17/08","MERCEARIA DA JU","01/05","Maceió",138.88,"Ju/Wellington","mercearia"),
 t(17,"17/08","MP*MP","","Osasco",21.30,"Ju/Wellington"),
 t(18,"24/08","NETFLIX.COM","","São Paulo",59.90,"Rosa","Netflix"),
 t(19,"21/12","IMPÉRIO MÓVEIS E ELETR","09/12","Recife",298.58,"Evane","geladeira"),
 t(20,"23/12","MP*CELULAR","08/12","Maceió",199.75,"Wedja","celular"),
 t(21,"05/02","MUNDO TECHS","07/10","Maceió",140,"Wedja","Mundo Techs"),
 t(22,"09/03","AMAZON BR","06/10","São Paulo",218.99,"Kauany","televisão"),
 t(23,"26/03","GUICHÊ WEB","05/05","Votuporanga",128.95,"Aianny"),
 t(24,"06/04","JIM.COM VIVIANE ALVES PAU","05/12","Piracicaba",533.33,"Rosa","material de construção",{agreement:{person:"Leandro",amount:266.66,note:"metade do material de construção"}}),
 t(25,"20/05","SHOPEE *IdealizaLaser","04/05","Brasília",56.35,"Wedja","Idealiza Laser"),
 t(26,"26/05","SHOPEE *fentselegance","03/03","Aracaju",61.07,"Wedja","Fents Elegance"),
 t(27,"28/05","MP*JAODESIGNER","03/03","Osasco",379.76,"Joao Lucas","João Designer"),
 t(28,"28/05","SHOPEE *GRUPOVNX","03/06","Belo Horizonte",108.50,"Rosa","maquininha"),
 t(29,"29/05","MP*JOAORODRIGUESALVES","03/04","Osasco",170.89,"Joao Lucas"),
 t(30,"30/05","MP*TECHMUNDO","03/04","Osasco",419.75,"Aianny","Techmundo"),
 t(31,"31/05","64269627AdrianaDa","03/04","Maceió",57.50,"Aianny"),
 t(32,"03/06","ACQUA PARK","03/03","Maceió",70.75,"Wedja","Acqua Park"),
 t(33,"03/06","AMAZONMKTPLC*ERICJOSEG","03/07","Maringá",155.71),
 t(34,"03/06","AMAZONMKTPLC*ERICJOSEG","04/07","Maringá",155.71),
 t(35,"03/06","AMAZONMKTPLC*ERICJOSEG","05/07","Maringá",155.71),
 t(36,"03/06","AMAZONMKTPLC*ERICJOSEG","06/07","Maringá",155.71),
 t(37,"03/06","AMAZONMKTPLC*ERICJOSEG","07/07","Maringá",155.71),
 t(38,"11/06","RIACHUELO FILIAL 153","03/05","Maceió",71.99,"Wedja","Riachuelo"),
 t(39,"12/06","ABYS CALÇADOS - 0185","03/03","Maceió",69.99,"Rosa","chinelo do Daniel; compra feita por Katiane"),
 t(40,"12/06","TORRA TORRA","03/03","Maceió",89.98,"Rosa","roupas"),
 t(41,"24/06","51431434Tamara","02/02","Maceió",65.50,"Ju/Wellington"),
 t(42,"24/06","POSTO CARANGO","02/02","Maceió",50,"Rosa","combustível"),
 t(43,"26/06","LOJAS RENNER FL 96","02/03","Maceió",59.96,"Aianny","Renner"),
 t(44,"28/06","AiannyGessyca","02/02","Maceió",90,"Aianny"),
 t(45,"30/06","MP*TECHMUNDO","02/05","Maceió",329.60,"Aianny","Techmundo"),
 t(46,"06/07","ABYS MODAS LTDA - 1157","02/02","Maceió",49.99,"Rosa","tênis"),
 t(47,"07/07","AMAZONMKTPLC*DNFCOMERC","02/04","São Paulo",47.50,"Rosa","selagem para Kauany"),
 t(48,"07/07","MERCADOLIVRE*MERCADOLIVRE","02/02","Palhoça",190.18,"Kauany","chapinha"),
 t(49,"07/07","MP*TECHMUNDO","02/02","Maceió",59.71,"Wedja","Techmundo"),
 t(50,"08/07","MERCADOLIVRE*MERCADOLI","02/03","São Paulo",83.30,"Ju/Wellington","Mercado Livre"),
 t(51,"09/07","ONESTYLLO","02/02","Maceió",132.50,"Ju/Wellington","Onestyllo"),
 t(52,"10/07","MTD*AMORSAUDE MACEIO C","02/02","Maceió",93.75,"Rosa","exame de Wellington"),
 t(53,"11/07","MP*FRANCILEIDE","02/06","Maceió",226.66,"","ótica: óculos de Evane e Wellington",{shares:[{owner:"Aianny",amount:113.33,dueNow:113.33,note:"óculos de Evane"},{owner:"Ju/Wellington",amount:113.33,dueNow:113.33,note:"óculos de Wellington"}]}),
 t(54,"19/07","ANTONIO CONSTRUCA","02/03","Maceió",113.33,"Ju/Wellington","Antonio Construção"),
 t(55,"20/07","ANTONIO CONSTRUCA","02/02","Maceió",56.50,"Ju/Wellington","Antonio Construção"),
 t(56,"21/07","CASA VIEIRA CENTRO","02/02","Maceió",52.11,"Rosa","Casa Vieira"),
 t(57,"24/07","NETFLIX.COM","","São Paulo",59.90,"Rosa","Netflix"),
 t(58,"25/07","Narcisoenxovais","01/02","Maceió",79.93,"Rosa","Narciso Enxovais"),
 t(59,"27/07","ANUIDADE DIFERENCIADA","06/12","-",9.90,"Rosa","anuidade"),
 t(60,"27/07","AmoreAlimentos","01/02","Maceió",60.50),
 t(61,"27/07","DESCONTO PROGRESSIVO ANUIDADE","","-",-9.90,"Rosa","desconto de anuidade"),
 t(62,"28/07","DINETE REIS","","Maceió",77,"Wedja"),
 t(63,"28/07","HNA","01/05","Maceió",47.36,"Wedja","eletricário"),
 t(64,"28/07","JEFFERSON BARRETO MUNI","","Maceió",66,"Wedja"),
 t(65,"28/07","JIM.COM 64487001 WEDJA SA","01/05","Maceió",364.26,"Wedja"),
 t(66,"28/07","MP*WEDJASANTOSAL","01/02","Maceió",35.06,"Wedja"),
 t(67,"28/07","Narcisoenxovais","01/05","Maceió",46.02,"Wedja","Narciso Enxovais"),
 t(68,"28/07","SEG CART PROTEGIDO CLASSI","","-",-6.90,"Rosa","crédito do seguro"),
 t(69,"28/07","TikTok Shop *TikTok Shop","","São Paulo",22.18),
 t(70,"28/07","TikTok Shop *TikTok Shop","","São Paulo",115),
 t(71,"27/07","ANUIDADE DIFERENCIADA","06/12","-",4.95,"Rosa","anuidade do cartão adicional"),
 t(72,"27/07","DESCONTO PROGRESSIVO ANUIDADE","","-",-4.95,"Rosa","desconto da anuidade"),
 t(73,"04/08","SEGURO CARTÃO PROTEGIDO C","","-",5.90,"Rosa","seguro do cartão adicional")
];

const STORAGE="painel-financeiro-setembro-v1";
const INVOICE_STORAGE="painel-financeiro-faturas-v1";
let transactions=load();
let invoices=loadInvoices();
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const num=v=>Number(String(v??0).replace(",","."))||0;
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function load(){try{return JSON.parse(localStorage.getItem(STORAGE))||structuredClone(INITIAL)}catch{return structuredClone(INITIAL)}}
function loadInvoices(){try{return JSON.parse(localStorage.getItem(INVOICE_STORAGE))||structuredClone(INITIAL_INVOICES)}catch{return structuredClone(INITIAL_INVOICES)}}
function persist(){localStorage.setItem(STORAGE,JSON.stringify(transactions))}
function persistInvoices(){localStorage.setItem(INVOICE_STORAGE,JSON.stringify(invoices))}
function allocations(tx){const normalized=a=>({...a,payTo:a.payTo??(a.owner&&a.owner!=="Rosa"?"Rosa":""),variationNote:a.variationNote||""});return tx.shares?.length?tx.shares.map(normalized):tx.owner?[normalized({owner:tx.owner,amount:tx.amount,dueNow:tx.dueNow,note:tx.note,payTo:tx.payTo,variationNote:tx.variationNote})]:[]}
function ownerTotals(){const totals=Object.fromEntries(OWNERS.map(o=>[o,{total:0,due:0,count:0,collect:0,pending:0,covers:0}]));transactions.forEach(tx=>{allocations(tx).forEach(a=>{if(!totals[a.owner])return;const pending=num(a.amount)-num(a.dueNow);totals[a.owner].total+=num(a.amount);totals[a.owner].due+=num(a.dueNow);totals[a.owner].pending+=pending;totals[a.owner].count++;if(a.payTo&&totals[a.payTo]&&a.payTo!==a.owner)totals[a.payTo].covers+=pending});if(tx.agreement&&totals[tx.owner])totals[tx.owner].collect+=num(tx.agreement.amount)});return totals}
function tag(owner){const color=COLORS[owner]||COLORS["Sem dono"];return `<span class="tag${owner?'':' unknown'}" style="--tag:${color}">${esc(owner||"Sem dono")}</span>`}
function render(){renderKpis();renderPeople();renderRows();renderAgreements();renderVariationRows();renderAnalytics();renderInvoices();bindActionButtons()}
function renderKpis(){const identified=transactions.filter(x=>allocations(x).length).reduce((s,x)=>s+x.amount,0);const unknown=transactions.filter(x=>!allocations(x).length).reduce((s,x)=>s+x.amount,0);const launches=transactions.reduce((s,x)=>s+x.amount,0);const balance=-900.40,final=7289.55;document.querySelector("#kpis").innerHTML=[
 ["VALOR DA FATURA",money(final),"Após o crédito anterior",""],["LANÇAMENTOS",money(launches),"Conferido com a fatura",Math.abs(launches-8189.95)<.01?"ok":"warn"],["IDENTIFICADO",money(identified),`${(identified/launches*100).toFixed(1).replace('.',',')}% dos lançamentos`,"ok"],["SEM DONO",money(unknown),`${transactions.filter(x=>!allocations(x).length).length} compras para revisar`,unknown?"warn":"ok"]
 ].map(([l,v,s,c])=>`<article class="kpi ${c}"><span>${l}</span><strong>${v}</strong><small>${s}</small></article>`).join("")}
function renderPeople(){const totals=ownerTotals();document.querySelector("#peopleGrid").innerHTML=OWNERS.map(o=>{const x=totals[o],net=x.due+x.covers-x.collect,items=[];transactions.forEach(tx=>allocations(tx).filter(a=>a.owner===o).forEach(a=>items.push({tx,a})));return `<article class="person-card" style="--person:${COLORS[o]}"><div class="person-head"><span class="person-name">${esc(o)}</span><span class="person-count">${x.count} lançamentos</span></div><div class="person-total">${money(x.total)}</div><div class="person-sub">responsabilidade na fatura</div><div class="person-lines"><div><span>Combinado neste mês</span><strong>${money(x.due)}</strong></div>${x.pending?`<div><span>Pendente da própria parte</span><strong>${money(x.pending)}</strong></div>`:""}${x.covers?`<div class="cover"><span>Cobre pendências de quem paga para ${esc(o)}</span><strong>${money(x.covers)}</strong></div>`:""}${x.collect?`<div class="collect"><span>A cobrar de terceiros</span><strong>${money(x.collect)}</strong></div>`:""}${(x.collect||x.covers)?`<div><span>Valor efetivo neste mês</span><strong>${money(net)}</strong></div>`:""}</div><div class="person-actions"><button class="ghost" data-add-owner="${esc(o)}">+ Incluir valor</button></div><details class="launch-details"><summary>Ver ${items.length} lançamentos</summary><div class="launch-list">${items.map(({tx,a})=>`<div class="launch-item"><span><span class="original-label">NOME ORIGINAL</span><strong>${esc(tx.merchant)}</strong><small>${esc(tx.note||a.note||"Sem descrição")} · ${tx.date} ${esc(tx.installment)}${a.payTo?` · paga para ${esc(a.payTo)}`:""}</small></span><strong>${money(a.amount)}</strong><button class="edit-btn" data-edit="${tx.id}">Editar</button></div>`).join("")}</div></details></article>`}).join("")}
function renderRows(){const q=document.querySelector("#searchInput").value.toLowerCase(),of=document.querySelector("#ownerFilter").value,sf=document.querySelector("#statusFilter").value;const list=transactions.filter(tx=>{const as=allocations(tx);const text=[tx.merchant,tx.note,tx.location,...as.map(a=>a.owner)].join(" ").toLowerCase();const ownerOk=!of||as.some(a=>a.owner===of);const statusOk=!sf||(sf==="identified"&&as.length)||(sf==="unknown"&&!as.length)||(sf==="agreement"&&tx.agreement);return text.includes(q)&&ownerOk&&statusOk});document.querySelector("#purchaseRows").innerHTML=list.map(tx=>`<tr><td>${tx.date}</td><td><span class="original-label">NOME ORIGINAL</span><strong>${esc(tx.merchant)}</strong> <small>${esc(tx.installment)}</small><br><small>${esc(tx.location)}</small></td><td>${allocations(tx).map(a=>tag(a.owner)).join("")||tag("")}</td><td class="row-note">${esc(tx.note)}${tx.agreement?`<br><strong>Cobrar ${esc(tx.agreement.person)}: ${money(tx.agreement.amount)}</strong>`:""}</td><td class="money">${money(tx.amount)}</td><td><button class="edit-btn" data-edit="${tx.id}">Editar</button></td></tr>`).join("")||`<tr><td colspan="6">Nenhuma compra encontrada.</td></tr>`;document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEdit(Number(b.dataset.edit)));document.querySelectorAll("[data-add-owner]").forEach(b=>b.onclick=()=>openNew(b.dataset.addOwner))}
function renderAgreements(){const agreements=transactions.filter(x=>x.agreement);const varied=[];transactions.forEach(tx=>allocations(tx).forEach(a=>{if(Math.abs(num(a.amount)-num(a.dueNow))>.009)varied.push({tx,a})}));document.querySelector("#agreementGrid").innerHTML=[...agreements.map(tx=>`<article class="agreement-card"><p class="eyebrow">COBRANÇA</p><h3>${esc(tx.owner)} responde pela compra</h3><div class="agreement-amount">Cobrar ${money(tx.agreement.amount)}</div><dl><dt>De quem</dt><dd>${esc(tx.agreement.person)}</dd><dt>Compra</dt><dd>${esc(tx.merchant)}</dd><dt>Motivo</dt><dd>${esc(tx.agreement.note)}</dd><dt>Total no colo de ${esc(tx.owner)}</dt><dd>${money(tx.amount)}</dd></dl><button class="ghost" data-edit="${tx.id}">Editar acordo</button></article>`),...varied.map(({tx,a})=>`<article class="agreement-card"><p class="eyebrow">VARIAÇÃO DO MÊS</p><h3>${esc(a.owner)} pagará menos</h3><div class="agreement-amount">Pendente ${money(num(a.amount)-num(a.dueNow))}</div><dl><dt>Compra</dt><dd>${esc(tx.merchant)}</dd><dt>Responsabilidade</dt><dd>${money(a.amount)}</dd><dt>Paga agora</dt><dd>${money(a.dueNow)}</dd><dt>Paga para</dt><dd>${esc(a.payTo||"—")}</dd></dl><button class="ghost" data-edit="${tx.id}">Editar compra</button></article>`)].join("")||`<article class="info-card">Nenhuma variação adicional registrada.</article>`}
function renderVariationRows(){const filter=document.querySelector("#variationOwnerFilter").value,rows=[];transactions.forEach(tx=>allocations(tx).forEach((a,index)=>{if(!filter||a.owner===filter)rows.push({tx,a,index:tx.shares?.length?index:-1})}));document.querySelector("#variationRows").innerHTML=rows.map(({tx,a,index})=>`<tr><td><span class="original-label">NOME ORIGINAL</span><strong>${esc(tx.merchant)}</strong><br><small>${tx.date} ${esc(tx.installment)}</small></td><td>${tag(a.owner)}</td><td class="money">${money(a.amount)}</td><td><input class="cell-input" type="number" step="0.01" value="${num(a.dueNow).toFixed(2)}" data-var-due="${tx.id}:${index}"></td><td><input class="cell-input" value="${esc(a.payTo||"")}" placeholder="Ex.: Rosa" data-var-payto="${tx.id}:${index}"></td><td><input class="cell-input wide" value="${esc(a.variationNote||"")}" placeholder="Motivo ou ajuste" data-var-note="${tx.id}:${index}"></td><td><button class="primary compact-button" data-save-var="${tx.id}:${index}">Salvar</button></td></tr>`).join("")||`<tr><td colspan="7">Nenhum lançamento para este filtro.</td></tr>`;document.querySelectorAll("[data-save-var]").forEach(b=>b.onclick=()=>saveVariation(b.dataset.saveVar))}
function saveVariation(key){const [id,index]=key.split(":").map(Number),tx=transactions.find(x=>x.id===id),prefix=`${id}:${index}`;if(!tx)return;const due=num(document.querySelector(`[data-var-due="${prefix}"]`).value),payTo=document.querySelector(`[data-var-payto="${prefix}"]`).value.trim(),variationNote=document.querySelector(`[data-var-note="${prefix}"]`).value.trim();if(index>=0){Object.assign(tx.shares[index],{dueNow:due,payTo,variationNote})}else Object.assign(tx,{dueNow:due,payTo,variationNote});persist();render()}
function bindActionButtons(){document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEdit(Number(b.dataset.edit)));document.querySelectorAll("[data-add-owner]").forEach(b=>b.onclick=()=>openNew(b.dataset.addOwner))}
function renderAnalytics(){const totals=ownerTotals();const selected=document.querySelector("#analysisOwner").value||"Todos";renderInvoiceChart();const max=Math.max(...OWNERS.map(o=>totals[o].total));document.querySelector("#distributionChart").innerHTML=OWNERS.map(o=>`<div class="bar-row"><strong style="color:${COLORS[o]}">${esc(o)}</strong><div class="bar-track"><div class="bar-fill" style="--bar:${COLORS[o]};width:${max?totals[o].total/max*100:0}%"></div></div><span class="money">${money(totals[o].total)}</span></div>`).join("");const stats=selected==="Todos"?{title:"Visão geral",items:[["Total identificado",transactions.filter(x=>allocations(x).length).reduce((s,x)=>s+x.amount,0)],["Sem identificação",transactions.filter(x=>!allocations(x).length).reduce((s,x)=>s+x.amount,0)],["A receber em acordos",transactions.reduce((s,x)=>s+num(x.agreement?.amount),0)],["Pendências cobertas por Rosa",totals.Rosa.covers]]}:{title:selected,items:[["Responsabilidade",totals[selected].total],["Combinado neste mês",totals[selected].due],["Pendente",totals[selected].pending],["Cobre de outras pessoas",totals[selected].covers],["A cobrar",totals[selected].collect],["Valor efetivo neste mês",totals[selected].due+totals[selected].covers-totals[selected].collect]]};document.querySelector("#individualTitle").textContent=stats.title;document.querySelector("#individualStats").innerHTML=`<div class="stat-list">${stats.items.map(([l,v])=>`<div class="stat"><span>${l}</span><strong>${money(v)}</strong></div>`).join("")}</div>`;document.querySelector("#invoiceList").innerHTML=invoices.map(i=>`<div class="invoice-item"><span>${i.month.toUpperCase()} ${i.year}</span><strong>${money(i.total)}</strong><small>${esc(i.detail)}</small></div>`).join("")}
function renderInvoiceChart(){const c=document.querySelector("#invoiceChart"),ctx=c.getContext("2d"),dpr=devicePixelRatio||1,w=c.clientWidth,h=240;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const series=invoices.filter(i=>i.total>0),pad={l:52,r:28,t:25,b:42},vals=series.map(x=>x.total);if(vals.length<2){document.querySelector("#variationLabel").textContent="Aguardando histórico";return}const min=Math.min(...vals)*.88,max=Math.max(...vals)*1.06,x=i=>pad.l+i*(w-pad.l-pad.r)/(vals.length-1),y=v=>pad.t+(max-v)*(h-pad.t-pad.b)/(max-min);ctx.strokeStyle="#dfe4ee";ctx.lineWidth=1;for(let i=0;i<4;i++){const yy=pad.t+i*(h-pad.t-pad.b)/3;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke()}ctx.beginPath();vals.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.strokeStyle="#315ee7";ctx.lineWidth=3;ctx.stroke();ctx.font="12px Segoe UI";ctx.textAlign="center";series.forEach((it,i)=>{ctx.fillStyle="#315ee7";ctx.beginPath();ctx.arc(x(i),y(it.total),5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#697386";ctx.fillText(it.month.slice(0,3),x(i),h-14);ctx.fillStyle="#172033";ctx.font="bold 11px Segoe UI";ctx.fillText(money(it.total),x(i),y(it.total)-12);ctx.font="12px Segoe UI"});const prev=series.at(-2),current=series.at(-1),pct=(current.total-prev.total)/prev.total*100;document.querySelector("#variationLabel").textContent=`${pct>=0?"+":""}${pct.toFixed(1).replace('.',',')}% vs. ${prev.month.toLowerCase()}`}
function splitCents(total,count){const cents=Math.round(num(total)*100),base=Math.trunc(cents/count),remainder=cents-base*count;return Array.from({length:count},(_,i)=>(base+(i<remainder?1:0))/100)}
function selectedParticipants(){return [...document.querySelectorAll("[data-participant]")].map(x=>x.value).filter(Boolean)}
function participantOptions(selected=""){return `<option value="">Selecione uma pessoa</option>`+OWNERS.map(o=>`<option${o===selected?' selected':''}>${esc(o)}</option>`).join("")}
function renderParticipantEditor(selected=[],preserveShares=[]){const rows=document.querySelector("#participantRows");if(!rows)return;rows.innerHTML=[0,1,2].map(i=>`<label><span>Participante ${i+1}</span><select data-participant="${i}">${participantOptions(selected[i]||"")}</select><strong data-participant-value="${i}">—</strong></label>`).join("");rows.querySelectorAll("[data-participant]").forEach(select=>select.onchange=()=>{const choices=selectedParticipants();if(select.value&&choices.filter(x=>x===select.value).length>1){alert("Essa pessoa já participa da compra.");select.value=""}syncParticipantSplit()});syncParticipantSplit(preserveShares)}
function syncParticipantSplit(preserveShares=[]){const participants=selectedParticipants(),amount=num(document.querySelector("#editAmount").value),values=participants.length?splitCents(amount,participants.length):[];document.querySelectorAll("[data-participant-value]").forEach((el,i)=>el.textContent=participants[i]?money(values[i]):"—");const summary=document.querySelector("#participantSummary");if(!participants.length){summary.textContent="Sem divisão: o responsável principal assume o valor integral.";return}summary.textContent=`${participants.length} participante${participants.length>1?'s':''} · ${participants.map((p,i)=>`${p}: ${money(values[i])}`).join(" · ")}`;const oldByOwner=Object.fromEntries(preserveShares.map(s=>[s.owner,s]));document.querySelector("#editShares").value=participants.map((owner,i)=>{const old=oldByOwner[owner],sameValue=old&&Math.abs(num(old.amount)-values[i])<.009,due=sameValue?num(old.dueNow):values[i],payTo=old?.payTo??(owner!=="Rosa"?"Rosa":""),note=old?.variationNote||"";return `${owner} = ${String(values[i].toFixed(2)).replace('.',',')} = ${String(due.toFixed(2)).replace('.',',')} = ${payTo} = ${note}`}).join("\n")}
function fillEdit(tx,isNew=false){document.querySelector("#editId").value=isNew?"":tx.id;document.querySelector("#dialogTitle").textContent=isNew?"Novo lançamento":tx.merchant;document.querySelector("#editDate").value=tx.date||"";document.querySelector("#editInstallment").value=tx.installment||"";document.querySelector("#editMerchant").value=tx.merchant||"";document.querySelector("#editLocation").value=tx.location||"";document.querySelector("#editOwner").value=tx.owner||"";document.querySelector("#editNote").value=tx.note||"";document.querySelector("#editAmount").value=tx.amount||"";document.querySelector("#editDueNow").value=tx.dueNow??tx.amount??"";document.querySelector("#editPayTo").value=tx.payTo??(tx.owner&&tx.owner!=="Rosa"?"Rosa":"");document.querySelector("#editVariationNote").value=tx.variationNote||"";document.querySelector("#editShares").value=(tx.shares||[]).map(s=>`${s.owner} = ${String(s.amount).replace('.',',')} = ${String(s.dueNow).replace('.',',')} = ${s.payTo??(s.owner!=="Rosa"?"Rosa":"")} = ${s.variationNote||""}`).join("\n");renderParticipantEditor((tx.shares||[]).map(s=>s.owner),tx.shares||[]);document.querySelector("#editAmount").oninput=()=>syncParticipantSplit(tx.shares||[]);document.querySelector("#editAgreementPerson").value=tx.agreement?.person||"";document.querySelector("#editAgreementAmount").value=tx.agreement?.amount||"";document.querySelector("#editAgreementNote").value=tx.agreement?.note||"";document.querySelector("#editDialog").showModal()}
function openEdit(id){fillEdit(transactions.find(x=>x.id===id))}
function openNew(owner=""){fillEdit({owner,date:"",merchant:"",installment:"",location:"",amount:"",dueNow:"",note:""},true)}
function saveEdit(e){e.preventDefault();const id=Number(document.querySelector("#editId").value);let tx=id?transactions.find(x=>x.id===id):null;if(!tx){tx={id:Math.max(0,...transactions.map(x=>x.id))+1};transactions.push(tx)}tx.date=document.querySelector("#editDate").value.trim();tx.installment=document.querySelector("#editInstallment").value.trim();tx.merchant=document.querySelector("#editMerchant").value.trim()||"LANÇAMENTO MANUAL";tx.location=document.querySelector("#editLocation").value.trim();tx.owner=document.querySelector("#editOwner").value;tx.note=document.querySelector("#editNote").value.trim();tx.amount=num(document.querySelector("#editAmount").value);tx.dueNow=num(document.querySelector("#editDueNow").value);tx.payTo=document.querySelector("#editPayTo").value.trim();tx.variationNote=document.querySelector("#editVariationNote").value.trim();const lines=document.querySelector("#editShares").value.trim().split(/\n+/).filter(Boolean);tx.shares=lines.map(line=>{const [owner,amount,dueNow,payTo,variationNote]=line.split("=").map(x=>x.trim());return{owner,amount:num(amount),dueNow:num(dueNow||amount),payTo:payTo??(owner!=="Rosa"?"Rosa":""),variationNote:variationNote||""}}).filter(x=>x.owner&&x.amount);if(!tx.shares.length)delete tx.shares;const person=document.querySelector("#editAgreementPerson").value.trim(),amount=num(document.querySelector("#editAgreementAmount").value),note=document.querySelector("#editAgreementNote").value.trim();if(person&&amount)tx.agreement={person,amount,note};else delete tx.agreement;persist();document.querySelector("#editDialog").close();render()}
function pdfDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open("painel-financeiro-pdfs",1);req.onupgradeneeded=()=>req.result.createObjectStore("pdfs");req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function storePdf(id,file){const db=await pdfDb();return new Promise((resolve,reject)=>{const tx=db.transaction("pdfs","readwrite");tx.objectStore("pdfs").put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function readPdf(id){const db=await pdfDb();return new Promise((resolve,reject)=>{const req=db.transaction("pdfs").objectStore("pdfs").get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function removePdf(id){const db=await pdfDb();return new Promise((resolve,reject)=>{const tx=db.transaction("pdfs","readwrite");tx.objectStore("pdfs").delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function renderInvoices(){document.querySelector("#registeredInvoices").innerHTML=invoices.map(i=>`<article class="registered-card"><span class="status-pill ${i.status==='Classificada'?'ready':''}">${esc(i.status||"Aguardando classificação")}</span><h3>${esc(i.month)} ${i.year}</h3><strong>${money(i.total)}</strong><p class="file-name">${esc(i.file)}</p><div class="registered-actions">${i.hasBlob?`<button class="ghost" data-open-pdf="${esc(i.id)}">Abrir PDF</button><button class="ghost" data-remove-invoice="${esc(i.id)}">Remover</button>`:""}</div></article>`).join("");document.querySelectorAll("[data-open-pdf]").forEach(b=>b.onclick=async()=>{const blob=await readPdf(b.dataset.openPdf);if(!blob)return alert("O PDF não foi encontrado neste navegador.");window.open(URL.createObjectURL(blob),"_blank")});document.querySelectorAll("[data-remove-invoice]").forEach(b=>b.onclick=async()=>{if(!confirm("Remover esta fatura registrada e o PDF guardado?"))return;await removePdf(b.dataset.removeInvoice);invoices=invoices.filter(i=>i.id!==b.dataset.removeInvoice);persistInvoices();render()})}
async function handleInvoiceUpload(e){e.preventDefault();const file=document.querySelector("#invoicePdf").files[0];if(!file)return alert("Selecione um PDF.");const month=document.querySelector("#invoiceMonth").value,year=Number(document.querySelector("#invoiceYear").value),total=num(document.querySelector("#invoiceTotal").value),id=`${month.toLowerCase()}-${year}-${Date.now()}`;await storePdf(id,file);invoices.push({id,month,year,total,file:file.name,detail:"PDF guardado localmente; aguardando classificação",hasBlob:true,status:"Aguardando classificação"});persistInvoices();e.target.reset();document.querySelector("#invoiceYear").value=2026;document.querySelector("#selectedPdf").textContent="Nenhum PDF selecionado";render()}
function init(){const ownerOptions=`<option value="">Sem dono</option>`+OWNERS.map(o=>`<option>${o}</option>`).join("");document.querySelector("#editOwner").innerHTML=ownerOptions;document.querySelector("#ownerFilter").innerHTML+=OWNERS.map(o=>`<option>${o}</option>`).join("");document.querySelector("#analysisOwner").innerHTML=`<option>Todos</option>`+OWNERS.map(o=>`<option>${o}</option>`).join("");document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelector(`#${b.dataset.tab}`).classList.add("active");if(b.dataset.tab==="demonstrativos")setTimeout(renderAnalytics,20)});["searchInput","ownerFilter","statusFilter"].forEach(id=>document.querySelector(`#${id}`).addEventListener("input",renderRows));document.querySelector("#analysisOwner").onchange=renderAnalytics;document.querySelector("#saveEdit").onclick=saveEdit;document.querySelector("#addTransactionBtn").onclick=()=>openNew();document.querySelector("#printBtn").onclick=()=>window.print();document.querySelector("#invoicePdf").onchange=e=>document.querySelector("#selectedPdf").textContent=e.target.files[0]?.name||"Nenhum PDF selecionado";document.querySelector("#invoiceUploadForm").onsubmit=handleInvoiceUpload;document.querySelector("#exportBtn").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({version:2,scope:"Gestão de João Lucas - serviço familiar do cartão BV",transactions,invoices},null,2)],{type:"application/json"}));a.download="painel-financeiro-familiar.json";a.click();URL.revokeObjectURL(a.href)};document.querySelector("#importInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);transactions=data.transactions;if(data.invoices)invoices=data.invoices;persist();persistInvoices();render()}catch{alert("Arquivo inválido.")}};r.readAsText(f)};document.querySelector("#resetBtn").onclick=()=>{if(confirm("Restaurar todas as classificações e valores originais deste painel?")){transactions=structuredClone(INITIAL);persist();render()}};window.addEventListener("resize",()=>{if(document.querySelector("#demonstrativos").classList.contains("active"))renderAnalytics()});render()}
init();
const dropZone=document.querySelector(".drop-zone"),pdfInput=document.querySelector("#invoicePdf");["dragenter","dragover"].forEach(type=>dropZone.addEventListener(type,e=>{e.preventDefault();dropZone.style.borderColor="#315ee7"}));["dragleave","drop"].forEach(type=>dropZone.addEventListener(type,e=>{e.preventDefault();dropZone.style.borderColor=""}));dropZone.addEventListener("drop",e=>{const file=[...e.dataTransfer.files].find(f=>f.type==="application/pdf"||f.name.toLowerCase().endsWith(".pdf"));if(!file)return alert("Selecione um arquivo PDF.");const dt=new DataTransfer();dt.items.add(file);pdfInput.files=dt.files;document.querySelector("#selectedPdf").textContent=file.name});

