const PROFILE_STORAGE="painel-bv-profiles-v1";
const OWNER_STORAGE="painel-bv-owners-v1";
const BASE_COLORS={...COLORS};
const DEFAULT_PROFILES={
  "Rosa":{gender:"female",notes:"Centraliza as cobranças da família."},
  "Wedja":{gender:"female",notes:""},
  "Aianny":{gender:"female",notes:""},
  "Ju/Wellington":{gender:"couple",notes:"As cobranças normalmente são encaminhadas para Ju."},
  "Joao Lucas":{gender:"male",notes:"Responsável pelo levantamento financeiro."},
  "Kauany":{gender:"female",notes:"A televisão é paga para Rosa."},
  "Evane":{gender:"female",notes:""}
};
let profiles=JSON.parse(localStorage.getItem(PROFILE_STORAGE)||"null")||structuredClone(DEFAULT_PROFILES);
let activeProfile="",shareBlob=null;
const savedOwners=JSON.parse(localStorage.getItem(OWNER_STORAGE)||"null");
if(Array.isArray(savedOwners)&&savedOwners.length)OWNERS.splice(0,OWNERS.length,...savedOwners);
OWNERS.forEach(owner=>{if(profiles[owner]?.color)COLORS[owner]=profiles[owner].color});

function profileFor(owner){return {...DEFAULT_PROFILES[owner],...profiles[owner],color:profiles[owner]?.color||COLORS[owner]||"#596273"}}
function genderIcon(gender){return gender==="female"?"♀":gender==="male"?"♂":gender==="couple"?"⚭":"●"}
function effectivePayment(owner,totals=ownerTotals()){const x=totals[owner];return owner==="Rosa"?x.due+x.covers-x.collect:x.due}
function sumAllPayments(totals=ownerTotals()){return OWNERS.reduce((sum,owner)=>sum+effectivePayment(owner,totals),0)}
function switchTab(name){document.querySelectorAll(".tab,.view").forEach(x=>x.classList.remove("active"));document.querySelector(`.tab[data-tab="${name}"]`)?.classList.add("active");document.querySelector(`#${name}`)?.classList.add("active");if(name==="demonstrativos")setTimeout(renderAnalytics,20)}

render=function(){renderKpis();renderPeople();renderRows();renderAgreements();renderVariationRows();renderAnalytics();renderInvoices();bindActionButtons()};
renderKpis=function(){const totals=ownerTotals(),identified=transactions.filter(x=>allocations(x).length).reduce((s,x)=>s+x.amount,0),unknownTransactions=transactions.filter(x=>!allocations(x).length),unknown=unknownTransactions.reduce((s,x)=>s+x.amount,0),launches=transactions.reduce((s,x)=>s+x.amount,0),final=7289.55,sumAll=sumAllPayments(totals);document.querySelector("#kpis").innerHTML=`
  <article class="kpi"><span>VALOR DA FATURA</span><strong>${money(final)}</strong><small>Após o crédito anterior</small></article>
  <article class="kpi sum-card"><span>SOMA TUDO · ESTE MÊS</span><strong>${money(sumAll)}</strong><small>Soma dos valores efetivos dos quadrantes</small></article>
  <article class="kpi ${Math.abs(launches-8189.95)<.01?"ok":"warn"}"><span>LANÇAMENTOS</span><strong>${money(launches)}</strong><small>Conferido com a fatura</small></article>
  <article class="kpi ok"><span>IDENTIFICADO</span><strong>${money(identified)}</strong><small>${(identified/launches*100).toFixed(1).replace(".",",")}% dos lançamentos</small></article>
  <article class="kpi ${unknown?"warn":"ok"}"><span>SEM DONO</span><strong>${money(unknown)}</strong><div class="kpi-action"><small>${unknownTransactions.length} compras para revisar</small><button class="ghost" id="showUnknownBtn">Ver lançamentos</button></div></article>`;document.querySelector("#showUnknownBtn").onclick=()=>{document.querySelector("#statusFilter").value="unknown";document.querySelector("#ownerFilter").value="";document.querySelector("#searchInput").value="";switchTab("compras");renderRows()}};

renderPeople=function(){const totals=ownerTotals();document.querySelector("#peopleGrid").innerHTML=OWNERS.map(owner=>{const x=totals[owner],pay=effectivePayment(owner,totals),p=profileFor(owner),items=[];transactions.forEach(tx=>allocations(tx).filter(a=>a.owner===owner).forEach(a=>items.push({tx,a})));return `<article class="person-card" style="--person:${p.color}"><div class="person-head"><span class="person-identity"><span class="gender-icon">${genderIcon(p.gender)}</span><span class="person-name">${esc(owner)}</span></span><span class="person-count">${x.count} lançamentos</span></div><div class="person-total-row"><div><div class="person-total payment">${money(pay)}</div><div class="person-sub">pagará efetivamente neste mês</div></div><button class="ghost" data-profile="${esc(owner)}">Ver perfil</button></div><div class="person-lines"><div><span>Responsabilidade original</span><strong>${money(x.total)}</strong></div><div><span>Confirmado nas compras</span><strong>${money(x.due)}</strong></div>${x.pending?`<div><span>Pendente da própria parte</span><strong>${money(x.pending)}</strong></div>`:""}${x.covers?`<div class="cover"><span>Cobre quem paga para ${esc(owner)}</span><strong>${money(x.covers)}</strong></div>`:""}${x.collect?`<div class="collect"><span>A cobrar de terceiros</span><strong>${money(x.collect)}</strong></div>`:""}</div><div class="person-actions"><button class="ghost" data-add-owner="${esc(owner)}">+ Incluir valor</button></div><details class="launch-details"><summary>Ver ${items.length} lançamentos</summary><div class="launch-list">${items.map(({tx,a})=>`<div class="launch-item"><span><span class="original-label">NOME ORIGINAL</span><strong>${esc(tx.merchant)}</strong><small>${esc(tx.note||a.note||"Sem descrição")} · ${tx.date} ${esc(tx.installment)}${a.payTo?` · paga para ${esc(a.payTo)}`:""}</small></span><strong>${money(a.dueNow)}</strong><button class="edit-btn" data-edit="${tx.id}">Editar</button></div>`).join("")}</div></details></article>`}).join("")};

bindActionButtons=function(){document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openEdit(Number(b.dataset.edit)));document.querySelectorAll("[data-add-owner]").forEach(b=>b.onclick=()=>openNew(b.dataset.addOwner));document.querySelectorAll("[data-profile]").forEach(b=>b.onclick=()=>openProfile(b.dataset.profile))};
function installmentInfo(value){const match=String(value||"").match(/(\d+)\s*\/\s*(\d+)/);if(!match)return{label:value||"à vista/sem parcela",finishing:true};const current=Number(match[1]),total=Number(match[2]);return{label:`parcela ${current} de ${total}`,finishing:current>=total}}
function ownerItems(owner){const items=[];transactions.forEach(tx=>allocations(tx).forEach((a,index)=>{if(a.owner===owner)items.push({tx,a,index:tx.shares?.length?index:-1})}));return items}
function buildProfileMessage(owner){const totals=ownerTotals(),x=totals[owner],items=ownerItems(owner),pay=effectivePayment(owner,totals),ending=items.filter(({tx})=>installmentInfo(tx.installment).finishing),targets=[...new Set(items.map(({a})=>a.payTo).filter(Boolean))],targetLabel=targets.length?targets.join(" e "):owner==="Rosa"?"o cartão BV":"Rosa";const lines=[`Olá, ${owner}! Segue o resumo da sua participação na fatura deste mês:`,``,`💳 Participação total: ${money(x.total)}`,`✅ Valor combinado para este mês: ${money(pay)}`,`👤 Pagamento para: ${targetLabel}`];if(x.pending)lines.push(`⏳ Ficará pendente: ${money(x.pending)}`);if(x.covers)lines.push(`🤝 Valor que você cobrirá de outras pessoas: ${money(x.covers)}`);if(x.collect)lines.push(`📥 Valor a cobrar de terceiros: ${money(x.collect)}`);lines.push("","🧾 Compras:");items.forEach(({tx,a})=>{const inst=installmentInfo(tx.installment),description=tx.note||tx.merchant||"Compra",original=tx.note&&tx.merchant?` (${tx.merchant})`:"",adjusted=Math.abs(num(a.amount)-num(a.dueNow))>.009;lines.push(`• ${description}${original} — ${inst.label}: ${money(a.amount)}`);if(adjusted)lines.push(`  ↳ Pagará ${money(a.dueNow)} neste mês${a.variationNote?` — ${a.variationNote}`:""}.`)});if(ending.length){lines.push("","🎉 Compras que terminam neste mês:");ending.forEach(({tx})=>lines.push(`• ${tx.note||tx.merchant} — ${installmentInfo(tx.installment).label}.`))}lines.push("",`💰 Total para pagar agora: ${money(pay)}`,"","Se encontrar alguma diferença, me avise para eu corrigir.");return lines.join("\n")}
function renderProfile(owner){const totals=ownerTotals(),x=totals[owner],items=ownerItems(owner),p=profileFor(owner),pay=effectivePayment(owner,totals),ending=items.filter(({tx})=>installmentInfo(tx.installment).finishing).length;document.querySelector("#profileTitle").textContent=owner;document.querySelector("#profileName").value=owner;document.querySelector("#profileGender").value=p.gender||"person";document.querySelector("#profileColor").value=p.color;document.querySelector("#profileNotes").value=p.notes||"";document.querySelector("#profileSummary").innerHTML=[["PAGARÁ NO MÊS",pay],["RESPONSABILIDADE",x.total],["PENDENTE",x.pending],["TERMINANDO",ending]].map(([label,value],i)=>`<div class="profile-stat"><span>${label}</span><strong>${i===3?value:money(value)}</strong></div>`).join("");document.querySelector("#profilePurchases").innerHTML=items.map(({tx,a,index})=>{const inst=installmentInfo(tx.installment);return `<div class="profile-purchase"><div><span class="original-label">NOME ORIGINAL</span><strong>${esc(tx.merchant)}</strong><small>${esc(tx.note||"Sem descrição")} · ${tx.date||"sem data"} · ${inst.label}</small>${inst.finishing?`<small class="finishing">Termina neste mês</small>`:""}</div><div><small>Responsabilidade</small><strong>${money(a.amount)}</strong></div><label>Pagará agora<input type="number" step="0.01" value="${num(a.dueNow).toFixed(2)}" data-profile-due="${tx.id}:${index}"></label><button class="ghost" data-profile-save="${tx.id}:${index}">Salvar</button></div>`}).join("");document.querySelector("#profileMessage").value=buildProfileMessage(owner);document.querySelectorAll("[data-profile-save]").forEach(b=>b.onclick=()=>{saveProfilePayment(b.dataset.profileSave);renderProfile(activeProfile)})}
function openProfile(owner){activeProfile=owner;renderProfile(owner);document.querySelector("#profileDialog").showModal()}
function saveProfilePayment(key){const [id,index]=key.split(":").map(Number),tx=transactions.find(x=>x.id===id),input=document.querySelector(`[data-profile-due="${key}"]`);if(!tx||!input)return;if(index>=0)tx.shares[index].dueNow=num(input.value);else tx.dueNow=num(input.value);persist();render()}
function saveProfile(){const oldName=activeProfile,newName=document.querySelector("#profileName").value.trim()||oldName,newProfile={gender:document.querySelector("#profileGender").value,color:document.querySelector("#profileColor").value,notes:document.querySelector("#profileNotes").value.trim()};if(newName!==oldName){const pos=OWNERS.indexOf(oldName);if(pos>=0)OWNERS[pos]=newName;transactions.forEach(tx=>{if(tx.owner===oldName)tx.owner=newName;if(tx.payTo===oldName)tx.payTo=newName;tx.shares?.forEach(s=>{if(s.owner===oldName)s.owner=newName;if(s.payTo===oldName)s.payTo=newName});if(tx.agreement?.person===oldName)tx.agreement.person=newName});COLORS[newName]=newProfile.color;delete COLORS[oldName];delete profiles[oldName];activeProfile=newName}else COLORS[oldName]=newProfile.color;profiles[activeProfile]=newProfile;localStorage.setItem(PROFILE_STORAGE,JSON.stringify(profiles));localStorage.setItem(OWNER_STORAGE,JSON.stringify(OWNERS));persist();refreshOwnerSelects();render();renderProfile(activeProfile)}
async function copyProfileMessage(){const text=document.querySelector("#profileMessage").value;try{await navigator.clipboard.writeText(text)}catch{const area=document.querySelector("#profileMessage");area.select();document.execCommand("copy")}const button=document.querySelector("#copyProfileMessage");button.textContent="Mensagem copiada!";setTimeout(()=>button.textContent="Copiar mensagem",1800)}

function roundRectPath(ctx,x,y,w,h,r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h);return ctx}
function generateShareCanvas(){const totals=ownerTotals(),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=1080;canvas.height=1350;ctx.fillStyle="#f2f4f8";ctx.fillRect(0,0,1080,1350);ctx.fillStyle="#14275d";ctx.fillRect(0,0,1080,235);ctx.fillStyle="#fff";ctx.font="800 30px Segoe UI";ctx.fillText("PAINEL FAMÍLIA • CARTÃO BV",58,67);ctx.font="900 58px Segoe UI";ctx.fillText("Pagamentos do mês",58,134);ctx.font="700 25px Segoe UI";ctx.fillStyle="#d4ddf8";ctx.fillText(`SOMA TUDO  ${money(sumAllPayments(totals))}  •  VENC. 01/09/2026`,58,188);const cards=OWNERS.map(owner=>({owner,value:effectivePayment(owner,totals),x:totals[owner],profile:profileFor(owner)})),gap=22,left=48,top=270,w=(1080-left*2-gap)/2,h=225;cards.forEach((card,i)=>{const col=i%2,row=Math.floor(i/2),x=left+col*(w+gap),y=top+row*(h+gap);ctx.fillStyle=card.profile.color;roundRectPath(ctx,x,y,w,h,22).fill();ctx.fillStyle="#fff";ctx.font="800 25px Segoe UI";ctx.fillText(`${genderIcon(card.profile.gender)}  ${card.owner.toUpperCase()}`,x+26,y+43);ctx.font="900 45px Segoe UI";ctx.fillText(money(card.value),x+26,y+105);ctx.font="600 18px Segoe UI";ctx.globalAlpha=.9;ctx.fillText("PAGARÁ NESTE MÊS",x+26,y+135);ctx.font="600 16px Segoe UI";ctx.fillText(`Responsabilidade: ${money(card.x.total)}`,x+26,y+172);if(card.x.pending)ctx.fillText(`Pendente: ${money(card.x.pending)}`,x+26,y+198);if(card.owner==="Rosa"&&card.x.covers)ctx.fillText(`Cobre: ${money(card.x.covers)}`,x+280,y+198);ctx.globalAlpha=1});ctx.fillStyle="#172033";ctx.font="800 20px Segoe UI";ctx.fillText("Valores atualizados conforme os pagamentos confirmados no Painel Família.",48,1290);ctx.font="500 17px Segoe UI";ctx.fillStyle="#697386";ctx.fillText("Responsabilidades originais e pendências continuam registradas para conferência.",48,1320);return canvas}
function openShareImage(){const canvas=generateShareCanvas(),preview=document.querySelector("#sharePreview");preview.src=canvas.toDataURL("image/png");canvas.toBlob(blob=>shareBlob=blob,"image/png");document.querySelector("#shareDialog").showModal()}
function downloadShareImage(){if(!shareBlob)return;const a=document.createElement("a");a.href=URL.createObjectURL(shareBlob);a.download="painel-familia-pagamentos-setembro-2026.png";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function nativeShareImage(){if(!shareBlob)return;const file=new File([shareBlob],"painel-familia.png",{type:"image/png"});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:"Painel Família",text:"Demonstrativo dos pagamentos do cartão BV."});else downloadShareImage()}
function refreshOwnerSelects(){const options=OWNERS.map(o=>`<option>${esc(o)}</option>`).join("");document.querySelector("#editOwner").innerHTML=`<option value="">Sem dono</option>${options}`;document.querySelector("#ownerFilter").innerHTML=`<option value="">Todos os responsáveis</option>${options}`;document.querySelector("#analysisOwner").innerHTML=`<option>Todos</option>${options}`;document.querySelector("#variationOwnerFilter").innerHTML=`<option value="">Todas as pessoas</option>${options}`}

function exportPanelData(){const a=document.createElement("a"),payload={version:3,scope:"Gestão de João Lucas - serviço familiar do cartão BV",owners:[...OWNERS],transactions,invoices,profiles};a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));a.download="painel-financeiro-familiar.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importPanelData(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.transactions))throw new Error("Transações ausentes");transactions=data.transactions;if(Array.isArray(data.invoices))invoices=data.invoices;if(Array.isArray(data.owners)&&data.owners.length){OWNERS.splice(0,OWNERS.length,...data.owners);localStorage.setItem(OWNER_STORAGE,JSON.stringify(OWNERS))}if(data.profiles&&typeof data.profiles==="object"){profiles=data.profiles;localStorage.setItem(PROFILE_STORAGE,JSON.stringify(profiles))}OWNERS.forEach(owner=>{if(profiles[owner]?.color)COLORS[owner]=profiles[owner].color});persist();persistInvoices();refreshOwnerSelects();render()}catch{alert("Arquivo inválido.")}};reader.readAsText(file)}
function resetPanel(){if(!confirm("Restaurar classificações, valores e perfis originais deste painel?"))return;transactions=structuredClone(INITIAL);profiles=structuredClone(DEFAULT_PROFILES);OWNERS.splice(0,OWNERS.length,...Object.keys(DEFAULT_PROFILES));Object.keys(COLORS).forEach(key=>delete COLORS[key]);Object.assign(COLORS,BASE_COLORS);localStorage.removeItem(OWNER_STORAGE);localStorage.setItem(PROFILE_STORAGE,JSON.stringify(profiles));persist();refreshOwnerSelects();render()}
function activateEnhancements(){refreshOwnerSelects();document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));document.querySelector("#variationOwnerFilter").onchange=renderVariationRows;document.querySelector("#shareImageBtn").onclick=openShareImage;document.querySelector("#closeShareDialog").onclick=()=>document.querySelector("#shareDialog").close();document.querySelector("#downloadShareImage").onclick=downloadShareImage;document.querySelector("#nativeShareImage").onclick=nativeShareImage;document.querySelector("#closeProfileDialog").onclick=()=>document.querySelector("#profileDialog").close();document.querySelector("#saveProfile").onclick=saveProfile;document.querySelector("#copyProfileMessage").onclick=copyProfileMessage;document.querySelector("#exportBtn").onclick=exportPanelData;document.querySelector("#importInput").onchange=importPanelData;document.querySelector("#resetBtn").onclick=resetPanel;render()}
activateEnhancements();

