(function(){
const review=document.querySelector("#invoiceReview"),rowsBox=document.querySelector("#invoiceImportRows"),statusBox=document.querySelector("#invoiceParseStatus"),reconciliation=document.querySelector("#invoiceReconciliation");
let candidates=[],parsedSummary=null,readingToken=0;
const MONTHS=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
function plain(value=""){return String(value).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/^(MP\s*\*?|PAG\*|MERCADOPAGO\*|MERCADOLIVRE\*)/g,"").replace(/[^A-Z0-9]+/g," ").trim()}
function amountFrom(value=""){const negative=/\(-\)|^-/.test(value),number=value.replace(/[^\d,.-]/g,"").replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",",".").replace(/(?!^)-/g,"");return (negative?-1:1)*Math.abs(Number(number)||0)}
function similarity(a,b){a=plain(a);b=plain(b);if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return .9;const aa=new Set(a.split(" ").filter(x=>x.length>2)),bb=new Set(b.split(" ").filter(x=>x.length>2)),both=[...aa].filter(x=>bb.has(x)).length,total=new Set([...aa,...bb]).size;return total?both/total:0}
function historicalSuggestion(merchant){let best=null;transactions.forEach(tx=>{if(!allocations(tx).length)return;const score=similarity(merchant,tx.merchant);if(!best||score>best.score)best={tx,score}});if(!best||best.score<.55)return null;return{score:best.score,source:best.tx,owners:allocations(best.tx).map(a=>a.owner),note:best.tx.note||""}}
function groupPageRows(content){const groups=[];content.items.filter(item=>item.str?.trim()).forEach(item=>{const y=Math.round(item.transform[5]*2)/2,x=item.transform[4],found=groups.find(group=>Math.abs(group.y-y)<=1.5);(found||groups[groups.push({y,items:[]})-1]).items.push({x,text:item.str.trim()})});return groups.sort((a,b)=>b.y-a.y).map(group=>({y:group.y,items:group.items.sort((a,b)=>a.x-b.x)}))}
function parseTransactionRow(row,page){const items=row.items,dateIndex=items.findIndex(item=>/^\d{2}\/\d{2}$/.test(item.text));if(dateIndex<0)return null;const moneyIndex=items.findIndex((item,index)=>index>dateIndex&&/(?:R\$\s*)?[\d.]+,\d{2}$/.test(item.text)&&!/^\d{2}\/\d{2}$/.test(item.text));if(moneyIndex<0)return null;const valueItems=items.slice(dateIndex+1,moneyIndex+1),isNegative=valueItems.some(item=>item.text.includes("(-)"))||/^\s*-/.test(items[moneyIndex].text),amount=(isNegative?-1:1)*Math.abs(amountFrom(items[moneyIndex].text));if(!amount)return null;const middle=items.slice(dateIndex+1,moneyIndex).filter(item=>!/^R\$$/.test(item.text)&&!/^\(-\)$/.test(item.text));if(!middle.length)return null;const installmentIndex=middle.findIndex(item=>/^\d{2}\/\d{2}$/.test(item.text)),merchantItems=installmentIndex>=0?middle.slice(0,installmentIndex):middle.slice(0,Math.max(1,middle.length-1)),locationItems=installmentIndex>=0?middle.slice(installmentIndex+1):middle.slice(merchantItems.length),merchant=merchantItems.map(item=>item.text).join(" ").replace(/\s+/g," ").trim(),installment=installmentIndex>=0?middle[installmentIndex].text:"",location=locationItems.map(item=>item.text).join(" ").replace(/\s+/g," ").trim();if(!merchant||/^(DATA|TOTAL|VALOR|DESCRI)(?:\s|$)/i.test(merchant)||/PAGAMENTO EFETUADO/i.test(merchant))return null;return{date:items[dateIndex].text,merchant,installment,location,amount,page}}
function summaryFromLines(lines){const all=lines.join(" ").replace(/\s+/g," "),totalMatch=[...all.matchAll(/Total (?:desta fatura|da fatura).*?R\$\s*([\d.]+,\d{2})/gi)].at(-1),national=[...all.matchAll(/Total (?:nacional|de lan[^R]{0,30}nacionais).*?R\$\s*([\d.]+,\d{2})/gi)].at(-1),monthMatch=all.match(/fatura de\s+([A-Za-zÀ-ÿ]+)/i),yearMatch=all.match(/Vencimento:?.{0,20}(\d{2})\/(\d{2})\/(\d{4})/i);return{invoiceTotal:totalMatch?amountFrom(totalMatch[1]):0,nationalTotal:national?amountFrom(national[1]):0,month:monthMatch?.[1]||"",year:yearMatch?Number(yearMatch[3]):0}}
async function readPdf(file,token){statusBox.textContent="Lendo o PDF e reconstruindo os lançamentos…";const pdfjs=await import("./assets/pdfjs/pdf.mjs");pdfjs.GlobalWorkerOptions.workerSrc="./assets/pdfjs/pdf.worker.mjs";const bytes=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjs.getDocument({data:bytes}).promise,found=[],lines=[];let nationalTransactionsStarted=false;for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){if(token!==readingToken)return;statusBox.textContent=`Lendo página ${pageNumber} de ${pdf.numPages}…`;const page=await pdf.getPage(pageNumber),content=await page.getTextContent(),pageRows=groupPageRows(content);lines.push(...pageRows.map(row=>row.items.map(item=>item.text).join(" ")));pageRows.forEach(row=>{const rowText=plain(row.items.map(item=>item.text).join(" "));if(!rowText.startsWith("TOTAL")&&/^LAN.*AMENTOS NACIONAIS$/.test(rowText))nationalTransactionsStarted=true;if(!nationalTransactionsStarted)return;const parsed=parseTransactionRow(row,pageNumber);if(parsed)found.push(parsed)})}return{found,summary:summaryFromLines(lines)}}
function buildCandidate(tx,index){const duplicate=transactions.some(existing=>existing.date===tx.date&&plain(existing.merchant)===plain(tx.merchant)&&String(existing.installment||"")===String(tx.installment||"")&&Math.abs(num(existing.amount)-tx.amount)<.009),suggestion=historicalSuggestion(tx.merchant);return{...tx,index,duplicate,suggestion,selected:!duplicate,owners:suggestion?.owners||[]}}
function confidenceLabel(item){if(item.duplicate)return'<span class="import-confidence duplicate">JÁ EXISTE</span>';if(!item.suggestion)return'<span class="import-confidence unknown">SEM DONO</span>';return`<span class="import-confidence ${item.suggestion.score>.88?"high":"medium"}">${item.suggestion.score>.88?"HISTÓRICO FORTE":"REVISAR"}</span>`}
function renderReview(){const importedTotal=candidates.filter(x=>x.selected).reduce((sum,x)=>sum+x.amount,0),target=parsedSummary?.nationalTotal||0,diff=target?target-importedTotal:0;statusBox.textContent=`${candidates.length} lançamentos encontrados · ${candidates.filter(x=>x.duplicate).length} possível(is) duplicado(s)`;reconciliation.innerHTML=`<span>TOTAL EXTRAÍDO<strong>${money(importedTotal)}</strong></span><span>REFERÊNCIA DA FATURA<strong>${target?money(target):"Não localizada"}</strong></span><span class="${Math.abs(diff)<.02?"reconciled":"difference"}">DIFERENÇA<strong>${target?money(diff):"—"}</strong></span>`;rowsBox.innerHTML=candidates.map(item=>`<tr class="${item.duplicate?"import-duplicate":""}"><td><input type="checkbox" data-import-check="${item.index}" ${item.selected?"checked":""} ${item.duplicate?"disabled":""}></td><td>${esc(item.date)}</td><td><strong>${esc(item.merchant)}</strong><small>Página ${item.page}${item.amount<0?" · crédito/estorno":""}</small></td><td>${esc([item.installment,item.location].filter(Boolean).join(" · ")||"—")}</td><td>${confidenceLabel(item)}<select data-import-owner="${item.index}"><option value="">Sem dono</option>${OWNERS.map(owner=>`<option ${item.owners.includes(owner)?"selected":""}>${esc(owner)}</option>`).join("")}</select>${item.suggestion?.note?`<small>${esc(item.suggestion.note)}</small>`:""}</td><td class="money ${item.amount<0?"negative":""}">${money(item.amount)}</td></tr>`).join("");document.querySelectorAll("[data-import-check]").forEach(input=>input.onchange=()=>{candidates[Number(input.dataset.importCheck)].selected=input.checked;renderReview()});document.querySelectorAll("[data-import-owner]").forEach(select=>select.onchange=()=>{candidates[Number(select.dataset.importOwner)].owners=select.value?[select.value]:[]})}
async function analyzeSelectedPdf(file){const token=++readingToken;review.hidden=false;rowsBox.innerHTML='<tr><td colspan="6" class="import-loading">Analisando o documento…</td></tr>';reconciliation.innerHTML="";try{const result=await readPdf(file,token);if(!result)return;candidates=result.found.map(buildCandidate);parsedSummary=result.summary;if(parsedSummary.invoiceTotal)document.querySelector("#invoiceTotal").value=parsedSummary.invoiceTotal.toFixed(2);if(parsedSummary.year)document.querySelector("#invoiceYear").value=parsedSummary.year;if(parsedSummary.month){const option=[...document.querySelector("#invoiceMonth").options].find(opt=>plain(opt.value)===plain(parsedSummary.month));if(option)document.querySelector("#invoiceMonth").value=option.value}renderReview()}catch(error){console.error(error);statusBox.textContent="Não foi possível ler automaticamente este PDF. Você ainda pode guardá-lo e incluir as compras manualmente.";rowsBox.innerHTML='<tr><td colspan="6" class="import-error">Falha na leitura automática. O arquivo original não foi alterado.</td></tr>'}}
function copySuggestedShares(item){if(!item.owners.length)return{owner:"",shares:[]};if(item.owners.length===1)return{owner:item.owners[0],shares:[]};const values=splitCents(item.amount,item.owners.length);return{owner:item.owners.join(" e "),shares:item.owners.map((owner,index)=>({owner,amount:values[index],dueNow:values[index],payTo:owner==="Rosa"?"":"Rosa",variationNote:"",note:item.suggestion?.note||""}))}}
async function confirmImport(){const selected=candidates.filter(item=>item.selected&&!item.duplicate);if(!selected.length)return alert("Selecione ao menos um lançamento para importar.");const month=document.querySelector("#invoiceMonth").value,year=Number(document.querySelector("#invoiceYear").value),total=num(document.querySelector("#invoiceTotal").value),file=document.querySelector("#invoicePdf").files[0],alreadyRegistered=invoices.some(invoice=>invoice.month===month&&Number(invoice.year)===year&&Math.abs(num(invoice.total)-total)<.01);if(!alreadyRegistered&&file&&month&&year&&total){const invoiceId=`${month.toLowerCase()}-${year}-${Date.now()}`;await storePdf(invoiceId,file);invoices.push({id:invoiceId,month,year,total,file:file.name,detail:"PDF analisado e lançamentos importados",hasBlob:true,status:"Classificada"});persistInvoices()}let nextId=Math.max(0,...transactions.map(tx=>Number(tx.id)||0))+1;selected.forEach(item=>{const suggestion=copySuggestedShares(item),singleOwner=suggestion.shares.length?"":suggestion.owner;transactions.push({id:nextId++,date:item.date,merchant:item.merchant,location:item.location,installment:item.installment,amount:item.amount,owner:singleOwner,note:item.suggestion?.note||"Importado do PDF; revisar descrição.",dueNow:item.amount,payTo:singleOwner&&singleOwner!=="Rosa"?"Rosa":"",variationNote:"",agreement:null,shares:suggestion.shares})});persist();render();statusBox.textContent=`${selected.length} lançamentos importados. Os totais e perfis já foram recalculados.`;document.querySelector("#confirmInvoiceImport").disabled=true;document.querySelector(".tab[data-tab='compras']").click()}
document.querySelector("#invoicePdf").addEventListener("change",event=>{const file=event.target.files[0];if(file)analyzeSelectedPdf(file)});
document.querySelector("#confirmInvoiceImport").onclick=confirmImport;
document.querySelector("#cancelInvoiceImport").onclick=()=>{readingToken++;candidates=[];review.hidden=true};
document.querySelector("#selectAllImported").onchange=event=>{candidates.forEach(item=>{if(!item.duplicate)item.selected=event.target.checked});renderReview()};
})();
